spring:
  profiles: default
  application:
    name: categories-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: categories-db
server:
  host: http://localhost
  port: 8083
  servlet:
    context-path: /api/v1/category
  
---
spring:
  profiles: dev
  application:
    name: categories-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: categories-dev-db
server:
  host: http://localhost
  port: 8083
  servlet:
    context-path: /api/v1/category

---
spring:
  profiles: sit
  application:
    name: categories-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: categories-sit-db
server:
  host: http://localhost
  port: 8083
  servlet:
    context-path: /api/v1/category
---
spring:
  profiles: uat
  application:
    name: categories-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: categories-uat-db
server:
  port: 8080
  
---
spring:
  profiles: pat
  application:
    name: categories-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: categories-pat-db
server:
  host: http://localhost
  port: 8083
  servlet:
    context-path: /api/v1/category

---
spring: 
  profiles: prod
  application:
    name: categories-api
  data:
    mongodb:
      uri: mongodb://test:Test123@mongodb.default.svc.cluster.local/OSC
server: 
  host: http://categories-api.default.svc.cluster.local
  port: 8080
  servlet:
    context-path: /api/v1/category